In [2]:
import numpy as np

RESULT_PATH = "result_matrix.txt"
MATRIX1_PATH = "matrix1.txt"
MATRIX2_PATH = "matrix2.txt"



matrix1 = np.loadtxt(MATRIX1_PATH, int, skiprows=1)
matrix2 = np.loadtxt(MATRIX2_PATH, int, skiprows=1)
result_matrix = np.loadtxt(RESULT_PATH, int, skiprows=1)


# Чтение матриц из файлов


print("Матрица 1:\n", matrix1)
print("Матрица 2:\n", matrix2)

def write_matrix_to_file(file_path, matrix):
    with open(file_path, 'w') as file:
        file.write(f"{len(matrix)} {len(matrix[0])}\n")
        for row in matrix:
            file.write(' '.join(map(str, row)) + '\n')


# Умножение матриц
result_matrix = np.matmul(matrix1, matrix2)

# Запись результата в файл
write_matrix_to_file('result_matrix.txt', result_matrix)

print("Матрицы перемножены успешно, и результат записан в файл 'result_matrix.txt'.")
print("Result:\n", result_matrix)

Матрица 1:
 [[39 50 96 90  1 15 18 17 60 59]
 [89 12 59 25 37 95 23 71 24 28]
 [80 34 59 52 51  5  6  2 31 42]
 [38 89 97 52 52 47  9 96 21 49]
 [57 93 71 63 94 90 91 86 60 19]
 [94  1 39 70  4 91 87 23 59 18]
 [26 45 41 51 17  8 99 48 24 98]
 [61 40  5 64 71 42 31 77 92 75]
 [94 45  9 88 37 59 57 78 30 59]
 [26 34  8 57 89 15 34  6  4 10]]
Матрица 2:
 [[ 26  99  98  29  24  75   3  72   6  57]
 [ 53  98  89  89  77  82  70  42  77  88]
 [ 14  57  48  77   9  10  23   9  75  60]
 [ 84  52  65  83  35   2  88  97  92  13]
 [ 69  64  72  49  63  68  31  70  78  39]
 [ 31  58   1  69  91  56  97  60  96  19]
 [ 78  97  53  10  54  88  83  64  52 100]
 [ 22  45  81  30   7  73  87  22  71  90]
 [ 37  63  13  25  31  90  71  12  74  17]
 [ 41  80  31  99  90  90  95  29  94  87]]
Матрицы перемножены успешно, и результат записан в файл 'result_matrix.txt'.
Result:
 [[19519 30858 23757 29558 18489 22608 28069 19429 33211 23360]
 [16766 31706 25156 24367 20445 28022 27476 22292 30834 24776]
 [